module.exports = {
  create: require('./create'),
  fork: require('./fork'),
  home: require('./home'),
  like: require('./like'),
  mypage: require('./mypage'),
  mypageId: require('./mypageId'),
  pid: require('./pid'),
  today: require('./today'),
  search: require('./search'),
  image: require('./image'),
  comment: require('./comment'),
  test: require('./test'),
  findLikeList: require('./findLikeList'),
  update: require('./update'),
  deleteBucket: require('./deleteBucket'),
};
